url: https://rannys.co.uk/
name: Ranny's
description: Independent coffee shop on Hempshaw Lane, Stockport. Good coffee, proper cake, no nonsense.
priceRange: ££
street: 407 Hempshaw Lane
locality: Stockport
region: Greater Manchester
postcode: SK1 4QA
country: GB
email: info@auntyrannys.com
instagramHandle: '@rannyscoffeeshop'
instagram: https://www.instagram.com/rannyscoffeeshop
facebook: https://facebook.com/61583039575566
previewImage: /assets/IMG_4077.jpeg
hours:
  - fromDay: Mo
    toDay: ''
    closed: true
    open: ''
    close: ''
  - fromDay: Tu
    toDay: Fr
    closed: false
    open: 07:00
    close: 16:00
  - fromDay: Sa
    toDay: ''
    closed: false
    open: 09:00
    close: 15:00
  - fromDay: Su
    toDay: ''
    closed: false
    open: 10:00
    close: 15:00
press:
  - name: Manchester's Finest
    url: https://www.manchestersfinest.com/places/rannys/
  - name: Stockport Nub News
    url: https://stockport.nub.news/news/local-news/new-mid-century-style-coffee-shop-opens-in-offerton-298750
  - name: Brik Studio
    url: https://www.instagram.com/reel/DZJ08wRi4Qt/
  - name: M.E.N
    url: https://www.manchestereveningnews.co.uk/whats-on/food-drink-news/no-airs-graces-stockport-cafe-34635425?fbclid=PAcGRvZgJleHRuA2FlbQIxMQBzcnRjBmFwcF9pZA81NjcwNjczNDMzNTI0MjcAAaeNtTqwErjzh_BOVNBX-AqxLn4pZoM-3yp1J_-xP7zlD2SLfa69f1Y4H3ZKpg_aem_Vu9Vl98xl1HAKG-cU6R49g
